version: '3'
services:
  jiraseven:
    container_name: jira_seven_postgres
    image: atlassian/jira-software:8.15
    ports:
      - "9090:8080"
    depends_on:
      - jirapostgres
    volumes:
      - /opt/jira
    networks:
      - network
  jirapostgres:
    container_name: my_postgres_for_jira
    image: postgres:11
    ports:
      - "65432:5432"
    environment:
      - 'POSTGRES_PASSWORD=admin'
    volumes:
      - /var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network
 
networks:
  network:
    driver: bridge
