CREATE ROLE admin WITH LOGIN ENCRYPTED PASSWORD 'admin' SUPERUSER;
CREATE DATABASE jira WITH OWNER admin ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE jira TO admin;
